<?php

declare(strict_types=1);

return [
    'meta' => ['description' => 'Öffentliche Meldungen durchsuchen und nach Kategorie filtern.'],
    'heading' => ['title' => 'Meldungen'],
    'hero' => ['title' => 'Meldungen und Dienste für Ihre Gemeinschaft', 'subtitle' => 'Melden Sie ein Problem und verfolgen Sie die Aktualisierungen im persönlichen Bereich.', 'cta_create' => 'Meldung senden', 'cta_practices' => 'Meine Vorgänge', 'cta_login' => 'Persönlichen Bereich öffnen', 'cta_register' => 'Konto erstellen'],
    'how' => ['title' => 'So funktioniert es', 'intro' => 'Melden Sie sich an, beschreiben Sie das Problem und markieren Sie den Ort. Ihre Vorgänge finden Sie im persönlichen Bereich.', 'step1_title' => 'Problem beschreiben', 'step1_body' => 'Erklären Sie, was passiert ist, und wählen Sie eine Kategorie.', 'step2_title' => 'Ort angeben', 'step2_body' => 'Fügen Sie den Ort und wichtige Details hinzu.', 'step3_title' => 'Updates verfolgen', 'step3_body' => 'Prüfen Sie Ihre Vorgänge nach der Anmeldung.'],
    'map' => ['caption' => 'Öffentliche Meldungen auf der Karte', 'cta_list' => 'Liste öffnen', 'details' => 'Details', 'type' => 'Meldungstyp', 'address' => 'Adresse', 'description' => 'Beschreibung', 'not_available' => 'Information nicht verfügbar', 'back_to_map' => 'Zurück zur Karte'],
    'list' => ['title' => 'Meldungsliste', 'subtitle' => 'Öffentliche Meldungen durchsuchen und nach Kategorie oder Suchbegriff filtern.', 'breadcrumb_current' => 'Meldungen', 'breadcrumb_aria' => 'Brotkrümelnavigation', 'filters_aria' => 'Meldungsfilter', 'search_label' => 'Nach Beschreibung suchen', 'search_placeholder' => 'z. B. Beleuchtung', 'category_legend' => 'Kategorie', 'no_categories' => 'Keine Kategorien verfügbar.', 'clear_filters' => 'Alle Filter löschen', 'results' => ':count Ergebnisse unter den 100 neuesten öffentlichen Meldungen.', 'view_mode_aria' => 'Ansicht', 'map' => 'Karte', 'list' => 'Liste', 'map_aria' => 'Karte der öffentlichen Meldungen', 'list_aria' => 'Öffentliche Meldungen', 'empty' => 'Keine öffentlichen Meldungen verfügbar.', 'empty_title' => 'Keine Ergebnisse', 'empty_hint' => 'Ändern Sie die Suche oder löschen Sie die Filter.', 'clear_filters_short' => 'Filter löschen', 'category_prefix' => 'Kategorie: :name', 'cta_heading' => 'Haben Sie ein Problem bemerkt?', 'cta_body' => 'Senden Sie eine Meldung und verfolgen Sie die Aktualisierungen.', 'cta_button' => 'Problem melden', 'track_heading' => 'Haben Sie bereits eine Meldung gesendet?', 'track_body' => 'Geben Sie den erhaltenen Code ein, um den Status zu prüfen.', 'track_button' => 'Meldung verfolgen', 'track' => 'Verfolgen'],
];
