<?php

declare(strict_types=1);

return [
    'meta' => ['description' => 'Consulta las incidencias abiertas y filtra los resultados por categoría.'],
    'heading' => ['title' => 'Incidencias'],
    'hero' => ['title' => 'Incidencias y servicios para tu comunidad', 'subtitle' => 'Envía una incidencia al Ayuntamiento y sigue las actualizaciones desde tu área personal.', 'cta_create' => 'Enviar una incidencia', 'cta_practices' => 'Mis trámites', 'cta_login' => 'Acceder al área personal', 'cta_register' => 'Crear una cuenta'],
    'how' => ['title' => 'Cómo funciona', 'intro' => 'Accede o crea una cuenta, describe el problema e indica su ubicación. Encontrarás tus trámites en el área personal.', 'step1_title' => 'Describe el problema', 'step1_body' => 'Explica lo ocurrido y elige la categoría adecuada.', 'step2_title' => 'Indica el lugar', 'step2_body' => 'Añade la ubicación y los datos útiles.', 'step3_title' => 'Sigue las novedades', 'step3_body' => 'Consulta tus trámites después de acceder.'],
    'map' => ['caption' => 'Incidencias públicas en el mapa', 'cta_list' => 'Ver la lista', 'details' => 'Detalles', 'type' => 'Tipo de incidencia', 'address' => 'Dirección', 'description' => 'Descripción', 'not_available' => 'Información no disponible', 'back_to_map' => 'Volver al mapa'],
    'list' => ['title' => 'Lista de incidencias', 'subtitle' => 'Consulta las incidencias públicas y filtra por categoría o palabra clave.', 'breadcrumb_current' => 'Incidencias', 'breadcrumb_aria' => 'Migas de pan', 'filters_aria' => 'Filtros de incidencias', 'search_label' => 'Buscar por descripción', 'search_placeholder' => 'p. ej. iluminación', 'category_legend' => 'Categoría', 'no_categories' => 'No hay categorías disponibles.', 'clear_filters' => 'Borrar todos los filtros', 'results' => ':count resultados entre las 100 incidencias públicas más recientes.', 'view_mode_aria' => 'Modo de vista', 'map' => 'Mapa', 'list' => 'Lista', 'map_aria' => 'Mapa de incidencias públicas', 'list_aria' => 'Incidencias públicas', 'empty' => 'No hay incidencias públicas disponibles.', 'empty_title' => 'Sin resultados', 'empty_hint' => 'Cambia la búsqueda o borra los filtros.', 'clear_filters_short' => 'Borrar filtros', 'category_prefix' => 'Categoría: :name', 'cta_heading' => '¿Has detectado un problema?', 'cta_body' => 'Envía una incidencia y sigue las actualizaciones.', 'cta_button' => 'Comunicar un problema', 'track_heading' => '¿Ya has enviado una incidencia?', 'track_body' => 'Introduce el código recibido para consultar su estado.', 'track_button' => 'Seguir una incidencia', 'track' => 'Seguir'],
];
